backend/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from rest_framework.schemas import get_schema_view
from rest_framework import renderers
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from .serializers import MyTokenObtainPairView


schema_url_patterns = [
    path('api/', include('json_inject.urls')),
]

urlpatterns = [
    path(
        'admin/password_reset/',
        auth_views.PasswordResetView.as_view(),
        name='admin_password_reset',
    ),
    path(
        'admin/password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done',
    ),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm',
    ),
    path(
        'reset/done/',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete',
    ),
    path('admin/', admin.site.urls),
    path('api/products/', include('products.urls')),
    path('', include('users.urls')),
    path('api/snippets/', include('snippets.urls')),
    path('api/user/', include('users.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/orders/', include('orders.urls')),
    path('api/inject/', include('json_inject.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('schema/', get_schema_view(title='My Project',
                                    description='a good API for a good frontend',
                                    version='1.0', patterns=schema_url_patterns,
                                    # renderer_classes=[renderers.JSONOpenAPIRenderer]
                                    ),
         name='openapi-schema'
         )

]

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import (register,
                    UserLogin,
                    UserLogout,
                    CustomUserCreate,
                    BlacklistTokenUpdateView,
                    UserDetailView
                    )


app_name = 'users'

urlpatterns = [
    # path('register/' , CustomUserCreate.as_view() , name='user-register') ,
    path('register/', register, name='user-register'),
    path('detail/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('login/', UserLogin.as_view(), name='user-login'),
    path('logout/', UserLogout.as_view(), name='user-logout'),
    path('logout/blacklist/', BlacklistTokenUpdateView.as_view(), name='blacklist')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<!-- remember to add lang -->
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="theme-color" content="#000000"/>


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">

    {% if page_title %}
        <title>{{ page_title }}</title>
    {% else %}
        <title>Django Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="#">Django Blog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                        aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="/admin">Admin</a>
                        <a class="nav-item nav-link" href="/api/products">API</a>
                        {#                        <a class="nav-item nav-link" href="{% url 'blog:blog-home' %}">Home</a>#}
                        {#                        <a class="nav-item nav-link" href="{% url 'blog:blog-about' %}">About</a>#}
                        {#                        <a class="nav-item nav-link" href="{% url 'tweet:tweet-home' %}">Tweet</a>#}
                        {#                        <a class="nav-item nav-link" href="{% url 'shop:shop-home' %}">Shop</a>#}
                        {#                        <a class="nav-item nav-link" href="{% url 'react-page' %}">React</a>#}
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if user.is_authenticated %}
                            {#<a class="nav-item nav-link" href="{% url 'blog:post-create' %}">New Post</a>#}
{#                            <a class="nav-item nav-link" href="{% url 'users:profile' %}">حساب کاربری</a>#}
                            <a class="nav-item nav-link" href="{% url 'users:user-logout' %}">خروج</a>
                        {% else %}
                            <a class="nav-item nav-link" href="{% url 'users:user-register' %}">ایجاد حساب</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-9">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                {% block content %}{% endblock %}
            </div>
            <div class="col-md-3">
                {% block side_bar %}{% endblock %}
            </div>
        </div>
    </main>

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
            crossorigin="anonymous"></script>


</body>
</html>

{% block script_block %}
{% endblock %}

templates/index.html
<!DOCTYPE html>
{% load render_bundle from webpack_loader %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% render_bundle 'frontend' %}
</body>
</html>